#SPDX-License-Identifier: MIT-0
---
- name: Get ansible user home directory
  ansible.builtin.set_fact:
    ansible_home: "{{ ansible_env.HOME }}"

- name: Copy docker-compose.yml to home directory
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ ansible_home }}/docker-compose.yml"

- name: Run Docker Compose from home directory
  ansible.builtin.command: "docker compose up -d"
  args:
    chdir: "{{ ansible_home }}"
