#SPDX-License-Identifier: MIT-0
---
ansible_os_family : "Debian"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - docker-buildx-plugin
  - python3-requests