# site.yml
- name: Apply selected roles
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'  # Accept new SSH keys automatically
  vars_files:
    - vault.yml  # Load sensitive variables from vault

  roles:
    - role: docker_install            # install Docker
    - role: docker_registry_setup     # setup private Docker registry and use vault for credentials
    - role: docker_compose            # apply Docker Compose file
   