name: CI - Build & Push to GHCR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./src
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/my-node-app:latest
          ghcr.io/${{ github.repository_owner }}/my-node-app:${{ github.sha }}
