---
- name: Add Docker GPG key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes  # Runs apt update after adding repo
  when: ansible_os_family == "Debian"

- name: Install Docker (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (CentOS)
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Docker (CentOS)
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group (optional)
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

